[package]
name = "effective_pom"
version = "0.1.0"
edition = "2021"

[dependencies]
base64 = "0.22.1"
dotenv = "0.15.0"
reqwest = { version = "0.12.7", features = ["blocking", "rustls-tls"] }
roxmltree = "0.20.0"
