
platform: bitbucket
base_url: https://dsigit.etat-de-vaud.ch/outils/git
# platform: github
# base_url: https://api.github.com
# user: bennekrouf

force_git_pull: false
force_maven_effective: false
trace_level: info
output_folder: tmp
enable_maven_analysis: true
enable_npm_analysis: true
enable_docker_analysis: true
enable_dotnet_analysis: true
enable_php_analysis: true
enable_jenkins_analysis: true 

equivalences:
  hibernate:
    - hibernate
  spring:
   - spring-framework
   - spring-context
   - spring-beans
 
  spring-boot:
   - spring-boot

  angular:
    - "@angular/core"
    - angular
    - angularjs
  java:
    - java-runtime
    - openjdk
    - jdk
  node:
    - nodejs
    - node
  richface:
    - richfaces
    - richface
