
platform: bitbucket
base_url: https://dsigit.etat-de-vaud.ch/outils/git
# platform: github
# base_url: https://api.github.com
# user: bennekrouf

force_git_pull: false
force_maven_effective: false
trace: info
output_folder: tmp

equivalences:
  spring:
    - spring-context
    - spring-beans
    - spring-framework
  angular:
    - "@angular/core"
    - angular
    - angularjs
  java:
    - java-runtime
    - openjdk
    - jdk
  node:
    - nodejs

