
platform: bitbucket
base_url: https://dsigit.etat-de-vaud.ch/outils/git
# platform: github
# base_url: https://api.github.com
# user: bennekrouf

force_git_pull: false
force_maven_effective: false
force_sled_db_sourcing: false
trace_level: info
output_folder: out
roadmap_folder: roadmap
enable_maven_analysis: true
enable_npm_analysis: true
enable_docker_analysis: false
enable_dotnet_analysis: false
enable_php_analysis: false
enable_jenkins_analysis: true

sources_priorities:
  - roadmap
  - ACT-INT
  - end-of-life

equivalences:
  hibernate:
    - hibernate
  spring:
   - spring-framework
   - spring-context
   - spring-beans
 
  spring-boot:
   - spring-boot

  angular:
    - "@angular/core"
    - angular
    - angularjs
  java:
    - java-runtime
    - openjdk
    - jdk
  node:
    - nodejs
    - node
    - nodeVersion
  richface:
    - richfaces
    - richface
