
platform: bitbucket
base_url: https://dsigit.etat-de-vaud.ch/outils/git
# platform: github
# base_url: https://api.github.com
# user: bennekrouf

force_git_pull: false
force_maven_effective: false
trace: INFO
output_folder: tmp
enable_maven_analysis: false
enable_npm_analysis: true
enable_docker_analysis: false
enable_dotnet_analysis: false
enable_php_analysis: false
enable_jenkins_analysis: false

equivalences:
  spring:
    - spring-context
    - spring-beans
    - spring-framework
  angular:
    - "@angular/core"
    - angular
    - angularjs
  java:
    - java-runtime
    - openjdk
    - jdk
  node:
    - nodejs

